build:
  environment:
    mongodb: true
  nodes:
    nodes:
      services:
        mongo: 3
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover