build:
  environment:
    mongodb: 4.0
  nodes:
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover