build:
  nodes:
    coverage:
      tests:
      services:  
        mongo: 4
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover